// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgwgmEvhBhwpBPMWTUhwzcmgy1JOjqxSg',
    appId: '1:761550322494:web:f43f586452cd6b6cd98a6f',
    messagingSenderId: '761550322494',
    projectId: 'semifinallab-2c880',
    authDomain: 'semifinallab-2c880.firebaseapp.com',
    storageBucket: 'semifinallab-2c880.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW8f48LUAvuQ89f9Ia1cM--q6hBJJd380',
    appId: '1:761550322494:android:82c5ca8aa551a638d98a6f',
    messagingSenderId: '761550322494',
    projectId: 'semifinallab-2c880',
    storageBucket: 'semifinallab-2c880.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkP-oNwkC3SsYBzfD8UvaT-2NAnuJlcNM',
    appId: '1:761550322494:ios:2620540c26058115d98a6f',
    messagingSenderId: '761550322494',
    projectId: 'semifinallab-2c880',
    storageBucket: 'semifinallab-2c880.appspot.com',
    iosClientId: '761550322494-qb1aar6j0plc8981cb0h870b8tu8g1lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.semiFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkP-oNwkC3SsYBzfD8UvaT-2NAnuJlcNM',
    appId: '1:761550322494:ios:2620540c26058115d98a6f',
    messagingSenderId: '761550322494',
    projectId: 'semifinallab-2c880',
    storageBucket: 'semifinallab-2c880.appspot.com',
    iosClientId: '761550322494-qb1aar6j0plc8981cb0h870b8tu8g1lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.semiFinal',
  );
}
